name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: â¬ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ§° Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: ğŸ“¦ Install dependencies
        run: npm i

      - name: ğŸ—ï¸ Build Angular SSR
        run: npm run build

      - name: List build files
        run: ls -R dist/

      - name: ğŸ“‚ Copy build to server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          port: ${{ secrets.PROD_PORT }}
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          source: |
            dist/
            ecosystem.config.js
          target: /home/webapp
          strip_components: 0

      - name: ğŸš€ SSH & Restart PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          port: ${{ secrets.PROD_PORT }}
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: |
            cd /home/webapp
            npm install --omit=dev
            pm2 startOrRestart ecosystem.config.js
